### ISSUE TITLE
Not able to add multiple products of same kind

### ISSUE THREAD

**Issue by arpittyagi102** [arpittyagi102/Humari-Dukan#17]
Hello contributers, I can see that in this reactjs project you can not add multiple instances of same product to the cart or store, I am using redux with react to store the data, Can anyone fix it ?
you can ask me if you need any help

**Comment by MRodriguez-M** [comment]
Has this issue been resolved yet? I was using the website and it seems like you can add any item to the cart as many times as you want. I have included a screenshot showing this.
![multiple-items-cart](https://github.com/arpittyagi102/Humari-Dukan/assets/41445895/a4601113-e68a-45f2-bf67-75bdda646e41)

**Comment by arpittyagi102** [comment]
No this issue has not been resolved
yes, you are right, this how it works when you add a product multiple times 
But what I want is, instead of showing three different names of single product it should show that this product has been added 3 times
Just like every other real e commerce website.
I hope i am clear

**Comment by MRodriguez-M** [comment]
Ok thank you, I better understand the issue now. Assign this to me please, I want to work on this issue

**Comment by arpittyagi102** [comment]
I have assigned you the issue
