### ISSUE TITLE
[UI improvement] can anyone fix the navbar?

### ISSUE THREAD

**Issue by arpittyagi102** [arpittyagi102/Humari-Dukan#21]
Hello contributors, the navbar of this website is disturbed by a contribution, can you fix it? 
design is made in bootstrap, ask me anything you need help with.

**Comment by akshayhere3001** [comment]
Can you point the particular improvement in UI?

**Comment by arpittyagirocks** [comment]
sure, the changes i am expecting in the navbar are :
- [ ] contents of the lower navbar are to be set evenly across the width 
- [ ] when scrolling lower navbar should go below ( z-index ) the upper navbar 
I hope i am clear 
Also, you can improve any other property you feel, it will be highly appreciated

**Comment by arpittyagirocks** [comment]
sure, the changes i am expecting in the navbar are :
- [ ] contents of the lower navbar are to be set evenly across the width 
- [ ] when scrolling lower navbar should go below ( z-index ) the upper navbar 
I hope i am clear 
* Also, you can improve any other property you feel, it will be highly appreciated

**Comment by Pulkitxm** [comment]
Hey @arpittyagirocks Can I get assigned for this one as well ?

**Comment by arpittyagirocks** [comment]
@Pulkitxm can you help me with #9 Adding payment gateway system in it?

**Comment by Pulkitxm** [comment]
Can you please elaborate ?

**Comment by arpittyagirocks** [comment]
@Pulkitxm On the final checkout page when the user tries to buy any product, it should show the window to actual payment for the product, you can find many youtube tutorials about it. I hope you will learn something new

**Comment by Pulkitxm** [comment]
and what about the navbar ? shall I start it and make a pr for this checkout page ?

**Comment by arpittyagirocks** [comment]
I think @akshayhere3001 is already working on navbar. you may proceed for the checkout page.
