### ISSUE TITLE
[bug] When clicking on Women's clothing category for the first time then it shows nothing

### ISSUE THREAD

**Issue by arpittyagi102** [arpittyagi102/Humari-Dukan#24]
Hello Contributers, there is a small bug in this reactjs project, when you click to the women category, then nothing appears, but when you click on any other category and then click on Women then it works properly.

**Comment by RoniSikder** [comment]
If this seems legit then I want to work on it

**Comment by arpittyagirocks** [comment]
I have assigned you the issue, you can start working

**Comment by RoniSikder** [comment]
It seems its working now check it now
