### ISSUE TITLE
Change <a> tag in Navbar component to Link

### ISSUE THREAD

**Issue by Akash1965** [arpittyagi102/Humari-Dukan#27]
Change `<a>` tag to `Link` in Navbar component since the Navbar component is wrapped with React router

**Comment by arpittyagirocks** [comment]
Hey @Akash1965, Yes you are right, thank you for pointing out

**Comment by aasimtaif** [comment]
Hi,  I am new to open source can I work on this issue

**Comment by aasimtaif** [comment]
thanks

**Comment by The-Alan-Turing** [comment]
Sorry, I just opened a PR on this.

**Comment by The-Alan-Turing** [comment]
> Hi, I am new to open source can I work on this issue

Sorry, I just opened a PR on this.
If you still intend to work on this, let me know. I would close this PR.

**Comment by aasimtaif** [comment]
You don't need the link tag in the navbar as it is not redirecting to any page if I change <a> to p or h tag the navbar will work as it is

**Comment by arpittyagirocks** [comment]
Hello contributors, i think he is right, it does not need the change. I will close this issue.
Also Have a look at my repository github.com/arpittyagirocks/LinkUp
It is under development and has a lot of scope for contributions.
I am planning to build it GREAT
