### ISSUE TITLE
Add a sorting feature for products

### ISSUE THREAD

**Issue by arpittyagi102** [arpittyagi102/Humari-Dukan#36]
Hello contributors, I want someone to create a sorting functionality to the products.
contact me if you need any help

**Comment by MRodriguez-M** [comment]
Hi, what kind of sorting functionality are you looking for?

**Comment by arpittyagi102** [comment]
Add a drop-down menu with 4 options 
- price ascending
- price descending
- ratings ascending
- ratings descending

When selecting them it should sort the visible products accordingly
> if you have a look at lower navbar it filters the products on the basis of their category using the filter(), implement the sorting similarly
> Data is extracted from JSON file src/components/products/productdata.json

**Comment by arpittyagi102** [comment]
Are you willing to work on this issue ?

**Comment by avinashji1302** [comment]
@arpittyagi102 I woukd like to work on this ! Please assign me this

**Comment by MRodriguez-M** [comment]
> Are you willing to work on this issue ?

Yes, I would like to take on this issue if possible

**Comment by arpittyagi102** [comment]
This issue has been solved !!
