### ISSUE TITLE
Cart componet's Responsiveness

### ISSUE THREAD

**Issue by avinashji1302** [arpittyagi102/Humari-Dukan#40]
<h2>Cart component's is not responsive</h2>

See The below Image 

![Tablet](https://github.com/arpittyagi102/Humari-Dukan/assets/91355822/53e1b46e-e888-41a0-92e8-775e5f2fb4a7)
![Mobile_ss](https://github.com/arpittyagi102/Humari-Dukan/assets/91355822/d2bcdc00-6918-457c-aa64-9dd461a467b5)

<h2>Please assign me this I can fix it </h2>

**Comment by arpittyagi102** [comment]
Hello @avinashji1302, Thank you for pointing out it out, I have assigned you the issue
you can start working on it.
