### ISSUE TITLE
UI is getting destorted Productlarge Componenet

### ISSUE THREAD

**Issue by avinashji1302** [arpittyagi102/Humari-Dukan#42]
<h2>Here is Picture</h2>

![cssmobile](https://github.com/arpittyagi102/Humari-Dukan/assets/91355822/328bcf62-410a-4cd6-91d8-6bd0cabffb76)

**Comment by arpittyagi102** [comment]
Hello @avinashji1302, Thank you for pointing out this issue, Clearly the website is not responsive.

**Comment by avinashji1302** [comment]
> Hello @avinashji1302, Thank you for pointing out this issue, Clearly the website is not responsive.

So please assign me....I will fix it  on Saturday

**Comment by arpittyagi102** [comment]
Sure, I have assigned you the issue.
