### ISSUE TITLE
Add the item counter button on the place of "Added to cart" button

### ISSUE THREAD

**Issue by arpittyagi102** [arpittyagi102/Humari-Dukan#50]
Hello contributors, when we click on a product, then click on `add to cart` it converts into `added to cart`, i want to change it to convert into a counter, in which you can increase the number of the product to buy or decrease, just like you will see in cart but with better designs, this project is made with Reactjs and Bootstrap

**Comment by kushalnigam0604** [comment]
I want to work on this issue..Do assign me.

**Comment by arpittyagi102** [comment]
Hello @kushalnigam0604, I have assigned you the issue, you may start working on it.
